version: "2"

services:
  nginx:
    container_name: inception_nginx
    image: inception/nginx
    build: srcs/requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - inception_app_data:/app
    networks:
      - inception_net
    restart: always

  wordpress:
    container_name: inception_wordpress
    image: inception/wordpress
    build: srcs/requirements/wordpress
    depends_on:
      - mariadb
    # ports:
      # - 9000:9000
    volumes:
      - inception_app_data:/app
    env_file: .env
    # environment:
      # - NODE_ENV=production
    networks:
      - inception_net
    restart: unless-stopped

  mariadb:
    container_name: inception_mariadb
    image: inception/mariadb
    build: srcs/requirements/mariadb
    ports:
      - 8589:3306
    volumes:
      - inception_db_data:/var/lib/mysql
      # - host:container
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

volumes:

  inception_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/wordpress/data

  inception_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/mariadb/data

networks:
  inception_net: